---

- include: RedHat.yml
  when: >
        ansible_distribution|lower == 'centos' or
        ansible_distribution|lower == 'red hat enterprise linux'

- include: repository.yml
  tags: repository
  when: >
        ansible_distribution|lower == 'debian' or 
        ansible_distribution.lower == 'ubuntu'

- include: packages.yml
  tags: packages
  when: >
        ansible_distribution|lower == 'debian' or 
        ansible_distribution.lower == 'ubuntu'

- include: config-cluster.yml
  when: rabbitmq_create_cluster

- include: config.yml

- include: service.yml

- include: cluster.yml
  when: (rabbitmq_create_cluster == true) and ( ansible_fqdn != rabbitmq_cluster_master )

- include: rabbitmq.yml
  when: 'not rabbitmq_create_cluster or (ansible_fqdn == rabbitmq_cluster_master)'

- meta: flush_handlers
